package api

import (
	"fmt"
	"net/http"
	"nz-cli/internal/commons"
	"path/filepath"

	tls_client "github.com/bogdanfinn/tls-client"
	"github.com/bogdanfinn/tls-client/profiles"
	cookiejar "github.com/juju/persistent-cookiejar"
)

var (
	SessionCookiesBase = filepath.Join(commons.GetConfigPath(), "nzCookies.json")
	AccountStateBase   = filepath.Join(commons.GetConfigPath(), "nzAccountState.json")
)

const (
	// User-Agent Header
	UserAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
)

// cookies jar for http.Client
var cookiesJar *cookiejar.Jar

// Main nz api client structure
type NZAPIClient struct {
	// account which we use
	account *AccountState

	// client generated by surf
	client tls_client.HttpClient

	// cookies (just to bypass CloudFlare, but they are usually null)
	cookies []*http.Cookie
}

// is user authorized and has access token
func (c NZAPIClient) Authorized() bool {
	return c.account != nil && c.account.AccessToken != ""
}

func (c *NZAPIClient) SetNewAccessToken(token string) {
	c.account.AccessToken = token
}

// get current account state
func (c NZAPIClient) Account() AccountState {
	return *c.account
}

// save current session
// returns error if something has gone wrong
func (c NZAPIClient) SaveSession() error {
	err := cookiesJar.Save()
	err = c.account.Save(AccountStateBase)
	return err
}

// load account from base
func (c *NZAPIClient) LoadAccount() error {
	state := AccountState{}
	err := state.Load(AccountStateBase)
	if err != nil {
		return fmt.Errorf("failed to load account state: %v", err)
	}
	c.account = &state

	return nil
}

// Create new api client
func NewApiClient() (apiClient *NZAPIClient, err error) {
	// New func loads from filename in private method newFromTime
	// that's why it has not Load() method ._.
	// p.s. i hate its dev
	cookiesJar, err = cookiejar.New(&cookiejar.Options{
		Filename: SessionCookiesBase,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to create cookie jar: %v", err)
	}

	// creating client with session, impersonating android chrome
	// because we use nz.ua mobile api
	options := []tls_client.HttpClientOption{
		tls_client.WithCookieJar(tls_client.NewCookieJar(
			tls_client.WithAllowEmptyCookies(),
		)),
		tls_client.WithTimeout(30),
		tls_client.WithClientProfile(profiles.Chrome_131),
		tls_client.WithNotFollowRedirects(),
	}

	client, err := tls_client.NewHttpClient(tls_client.NewNoopLogger(), options...)
	if err != nil {
		return nil, fmt.Errorf("faield to create fhttp client: %v", err)
	}

	return &NZAPIClient{
		client: client,
	}, nil
}
