package api

import (
	"fmt"
	"net/http"

	tls_client "github.com/bogdanfinn/tls-client"
	"github.com/bogdanfinn/tls-client/profiles"
)

// Main nz api client structure
type NZAPIClient struct {
	// account which we use
	account *AccountState

	// client generated by surf
	client tls_client.HttpClient

	// cookies (just to bypass CloudFlare, but they are usually null)
	cookies []*http.Cookie
}

// Is user authorized and has access token
func (c NZAPIClient) Authorized() bool {
	return c.account != nil && c.account.AccessToken != ""
}

// Set new access token instead of current one
func (c *NZAPIClient) SetNewAccessToken(token string) {
	c.account.AccessToken = token
}

// Get current account state
func (c NZAPIClient) Account() AccountState {
	return *c.account
}

// Save current session.
// Returns error if something has gone wrong
func (c NZAPIClient) SaveSession() error {
	err := c.account.Save(AccountStateBase)
	return err
}

// Load account from base
func (c *NZAPIClient) LoadAccount() error {
	state := AccountState{}
	err := state.Load(AccountStateBase)
	if err != nil {
		return fmt.Errorf("failed to load account state: %v", err)
	}
	c.account = &state

	return nil
}

// Returns tls client options
func tlsClientOptions() *[]tls_client.HttpClientOption {
	return &[]tls_client.HttpClientOption{
		tls_client.WithCookieJar(tls_client.NewCookieJar(
			tls_client.WithAllowEmptyCookies(),
		)),
		tls_client.WithTimeout(30),
		tls_client.WithClientProfile(profiles.Chrome_131),
		tls_client.WithNotFollowRedirects(),
	}
}

// Creates new http client with options
func newTlsClient() (*tls_client.HttpClient, error) {
	// creating client with session, impersonating android chrome
	// because we use nz.ua mobile api
	options := tlsClientOptions()
	client, err := tls_client.NewHttpClient(tls_client.NewNoopLogger(), *options...)
	if err != nil {
		return nil, fmt.Errorf("faield to create fhttp client: %v", err)
	}

	return &client, nil
}

// Create new api client
func NewAPIClient() (*NZAPIClient, error) {
	client, err := newTlsClient()
	if err != nil {
		return nil, fmt.Errorf("failed to create tls client: %v", err)
	}

	return &NZAPIClient{
		client: *client,
	}, nil
}
